security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        from_database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            form_login:
               check_path: login

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/prendre-rendez-vous,         roles: ROLE_PATIENT }
        - { path: ^/mes-rendez-vous,             roles: ROLE_PATIENT }
        - { path: ^/créer-rendez-vous,           roles: ROLE_PATIENT }
        - { path: ^/mes-ordonnances,             roles: ROLE_PATIENT }
        - { path: ^/view-prescription,           roles: ROLE_SECRETARY }
        - { path: ^/view-secretary,              roles: ROLE_SECRETARY }
        - { path: ^/manage-rendez-vous-agenda,   roles: [ROLE_SECRETARY, ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-créer-rendez-vous,    roles: [ROLE_SECRETARY, ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-rendez-vous,          roles: [ROLE_SECRETARY, ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-patient,              roles: [ROLE_SECRETARY, ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/view-secretary-admin,        roles: [ROLE_SECRETARY, ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-patient-prescription, roles: [ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-session,              roles: [ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-secretary-admin,      roles: [ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-secretary,            roles: [ROLE_SECRETARY_ADMIN, ROLE_PRACTITIONER, ROLE_PRACTITIONER_ADMIN]}
        - { path: ^/manage-practitioner,         roles: ROLE_PRACTITIONER_ADMIN }
        - { path: ^/manage-location,             roles: ROLE_PRACTITIONER_ADMIN }
        - { path: ^/manage-role,                 roles: ROLE_PRACTITIONER_ADMIN }
        - { path: ^/manage-rights,               roles: ROLE_PRACTITIONER_ADMIN }
        - { path: ^/manage-practitioner,         roles: ROLE_PRACTITIONER_ADMIN }
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
